app = "brandboda"
primary_region = "cdg"

[build]
  dockerfile = "Dockerfile"

# ðŸ”¥ Ø§Ù„ØªØºÙŠÙŠØ± Ù‡Ù†Ø§: Ø£Ù…Ø± Ø§Ù„ØªØ´ØºÙŠÙ„ Ø¨Ù‚Ù‰ run.py
[processes]
  app = "python3 run.py"

[[vm]]
  cpu_kind = "shared"
  cpus = 2
  memory_mb = 1024

[[swap]]
  size_mb = 512
